### ISSUE TITLE
Running an app with cocoa pods does not work.

### ISSUE THREAD

**Issue by edalford11** [ios-control/ios-sim#124]
Running the command ios-sim launch MyApp.app on an app that uses cocoapods gives the following error. 

Error Domain=NSPOSIXErrorDomain Code=22 "Unable to run app in Simulator" UserInfo=0x7fa532414e00 {NSLocalizedFailureReason=An error was encountered while running (Domain = NSPOSIXErrorDomain, Code = 22), NSUnderlyingError=0x7fa532609810 "Installation Failed", NSLocalizedRecoverySuggestion=An error occurred while preparing the app for installation (no bundle identifier was found at the expected path), NSLocalizedDescription=Unable to run app in Simulator}

The app works fine in the simulator when running from xcode.

**Comment by mokagio** [comment]
Hello all. I was having the same issue:

```
Error Domain=NSPOSIXErrorDomain Code=22 "Unable to run app in Simulator" UserInfo=0x7ffc1c900600 {NSLocalizedFailureReason=An error was encountered while running (Domain = NSPOSIXErrorDomain, Code = 22), NSUnderlyingError=0x7ffc1cb000c0 "Installation Failed", NSLocalizedRecoverySuggestion=An error occurred while preparing the app for installation (no bundle identifier was found at the expected path), NSLocalizedDescription=Unable to run app in Simulator}
```

I then noticed that the `frank build` command generated a new `Frank/frankfied_build/Applications/` folder, with a `APP_NAME.app` package inside. Changing the `APP_BUNDLE_PATH` in `env.rb` to that path "solved" the issue for me:

```ruby
# This constant must be set to the full, absolute path for your Frankified target's app bundle.
# See the "Given I launch the app" step definition in launch_steps.rb for more details
# APP_BUNDLE_PATH = File.expand_path( '../../../frankified_build/Frankified.app', __FILE__ )
APP_BUNDLE_PATH = File.expand_path( '../../../frankified_build/Applications/APP_NAME.app', __FILE__ ) 
```
