### ISSUE TITLE
Xcode 10.1 now ios-sim is missing iPhone XR,XS&XS-Max from list

### ISSUE THREAD

**Issue by jeffborg** [ios-control/ios-sim#235]
# Expected behavior

Running `ios-sim showdevicetypes` should show iPhone-XR,XS&XS-Max on Xcode 10.1

# Actual behavior.

Running `ios-sim showdevicetypes` Does not show these device types seems the names now have lower case R&S in them causing not to match and be removed

output from `xcrun simctl list`

```
iPhone Xs (com.apple.CoreSimulator.SimDeviceType.iPhone-XS)
iPhone Xs Max (com.apple.CoreSimulator.SimDeviceType.iPhone-XS-Max)
iPhone Xʀ (com.apple.CoreSimulator.SimDeviceType.iPhone-XR)
```

Note the small capital R and possibly s

# Steps to reproduce the problem

Update xcode 10 to 10.1

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [x ] 1. system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14 (18A391)
      Kernel Version: Darwin 18.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: supermac
      User Name: Jeffrey Borg (jeffrey)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 10 days 32 minutes

- [x ] 2. ios-sim --version
7.0.0
- [x ] 3. xcodebuild -version
Xcode 10.1
Build version 10B61
- [ x] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
- [x ] 5. node --version
v10.11.0

**Comment by kxws888** [comment]
me too

**Comment by brodybits** [comment]
Should be fixed in master now, will be part of upcoming 8.0 release. Unfortunately I cannot promise when it will happen.

**Comment by crabbydavis** [comment]
any word on when 8.0 will be released?
