### ISSUE TITLE
org questions for @shazron

### ISSUE THREAD

**Issue by brodybits** [ios-control/ios-sim#242]
There are some tools in this [ios-control](https://github.com/ios-control) organization that seem to have come from PhoneGap, which are needed to support the Cordova iOS platform. I think these tools *could* be used by non-Cordova users, not sure if there are any non-Cordova users though. In comparison I know that `cordova-node-xcode`, which *is* under Apache Cordova ownership, is used outside of Cordova (through some issues and PRs).

I will guess that these tools were put into the separate organization for licensing reasons, would love some confirmation on this part of the history.

More importantly, I have a feeling that we should add some more members and owners (see <https://github.com/orgs/ios-control/people>). Any thoughts? Is there anything I can do to help make this happen?

/cc @purplecabbage @dpogue

**Comment by dpogue** [comment]
Some of these projects are forks of earlier projects, and aren't licensed under the Apache 2 licence. For that reason, I don't believe they can be under Apache Cordova ownership.

**Comment by shazron** [comment]
> I think these tools could be used by non-Cordova users, not sure if there are any non-Cordova users though.
Not sure about ios-sim (have to check the forks), but I believe ios-deploy may be used by Unity, among others.

> I will guess that these tools were put into the separate organization for licensing reasons, would love some confirmation on this part of the history.
Yes.

> More importantly, I have a feeling that we should add some more members and owners (see https://github.com/orgs/ios-control/people). Any thoughts? Is there anything I can do to help make this happen?
I've given karma to you and the others to do just this.

**Comment by brodybits** [comment]
Thanks @shazron for the confirmation and for giving me the power!
