### ISSUE TITLE
List empty of devices simulator with Xcode 11

### ISSUE THREAD

**Issue by theblang** [ios-control/ios-sim#261]
See https://github.com/ios-control/ios-sim/issues/253

Same behavior, not able to `--list` or launch in `ios` after the update to Xcode 11 / iOS 13

`Error: Unhandled "error" event. ([ios-sim] Device type "com.apple.CoreSimulator.SimDeviceType.undefined" could not be found.
)`

**Comment by theblang** [comment]
Looks like one workaround for now is to open your `xcworkspace` file directly in Xcode. I'm able to launch my Cordova project that way instead.

**Comment by theblang** [comment]
Actually, I just realized we were on version `8.0.1`. It seems that with the most recent minor release, `8.0.2`, this isn't an issue.

**Comment by danguilherme** [comment]
Works in `8.0.2` indeed. Was using `ios-sim@next`, and it doesn't work in that version.

`ios-sim@next` resolves to the following version, at the time of writing:
```
$ ios-sim --version
ios-sim/9.0.0-dev.4 darwin-x64 node-v8.12.0
```
